### ISSUE TITLE
Technical Debt: Add a Currency Model for points

### ISSUE THREAD

**Issue by SSWnathanmills** [SSWConsulting/SSW.Rewards#100]
Adding a Currency Model

This change addresses technical debt as noted in the code here: 

https://github.com/SSWConsulting/SSW.Rewards/blob/983c49e2d69ff5a2adbce7cfbe0de8e6e2a5fce9/API/SSW.Rewards.Application/Reward/Commands/ClaimReward/ClaimRewardCommand.cs#L76

```csharp
       // TECH DEBT: the following logic is intended to 'debounce' reward
       // claiming, to prevent users claiming the same reward twice
       // within a 5 minute window. This workaround is only required on 
       // the current 'milestone' model for points. Once we move to the
       // 'currency' model, this will not be required anymore.
```

1. Add the ability to have QR codes that hold negative point values
2. Currently, points are calculated before the user information is sent to the application. During this calculation also include the negative QR codes.
3. Create unique QR codes for each prize that can be awarded and assign them the respective negative value of their point value.
4. Provide each office with these QR codes so that when a user claims and picks up a prize the user can scan the negative code.

Include a URL that explains to a new developer both models that the app users
1. Add an additional page to the Introductory popup in the Rewards app.
2. On the new page say something similar to, “The SSW Rewards app gives you the opportunity to accumulate points and win prizes. There are 2 ways that you can earn prizes with these points. First, by reaching specified milestones at which you will be rewarded the prize specific to that milestone. Second, by accumulating points, selecting a prize you would like, and then trading in the number of points that that prize is valued at.”

[AB#59098](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/59098)

**Comment by jerwinparker** [comment]
- [ ] test
- [ ] test2

**Comment by AndreasLengkeek** [comment]
@adamcogan  @MattGoldmanSSW @SSWnathanmills @jerwinparker Related database changes to separate achievements and rewards
https://ssw.visualstudio.com/SSW.Rewards/_workitems/edit/44263

**Comment by matt-goldman** [comment]
Done! This has now been implemented in v2.
