### ISSUE TITLE
NDC Feature: Giving away a prize to an attendee.

### ISSUE THREAD

**Issue by SSWnathanmills** [SSWConsulting/SSW.Rewards#103]
We could allow admins to create events and the speaker can be given a code to use during the event.

Each attendee can enter the code into the app to show that they are present. The app can then automatically pick a random attendee from those who entered the code.

Admins can see the whole list of attendees who entered the code on the event page in the app. Attendees can see that they are marked as attended.

The concept of an Event and the concept of a Speaker/Attendee and then connect the two.

[AB#57431](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57431)

**Comment by AndreasLengkeek** [comment]
test

**Comment by AndreasLengkeek** [comment]
Accidentally closed when merging related PR

**Comment by lukecookssw** [comment]
Closing this issue as it has been re-created with more detail in #377
