### ISSUE TITLE
Add SSW Logo to Title Bar

### ISSUE THREAD

**Issue by MattGoldmanSSW** [SSWConsulting/SSW.Rewards#121]
Email from product owner:

> Hey Matt G
> 
> can the SSW logo squeeze into the top - next to the title?
> 
> -a

![thumbnail_image001](https://user-images.githubusercontent.com/55862976/89473642-c3669d80-d7c6-11ea-970c-7e1703dd4c5d.jpg)

This can be implemented using TitleView: https://xamlabs.com/2019/10/06/xamarin-forms-add-ui-controls-to-navigation-bar-using-title-view/

**Comment by AndreasLengkeek** [comment]
New release fixes this issue!
![image](https://user-images.githubusercontent.com/10122406/94524184-9938d580-0275-11eb-82f2-c07548dc8209.png)
![image](https://user-images.githubusercontent.com/10122406/94524198-a35ad400-0275-11eb-8320-9505f3c03fe2.png)
![image](https://user-images.githubusercontent.com/10122406/94524213-a950b500-0275-11eb-968e-1d899f78e77a.png)
