### ISSUE TITLE
Tap title to scroll to top of screen

### ISSUE THREAD

**Issue by ghost** [SSWConsulting/SSW.Rewards#130]
![image](https://user-images.githubusercontent.com/55862976/94507116-60d3d000-0252-11eb-9134-4468311c2b7f.png)

[AB#57468](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57468)

**Comment by matt-goldman** [comment]
Superseded by v2 design.
