### ISSUE TITLE
Earn Points Page

### ISSUE THREAD

**Issue by ghost** [SSWConsulting/SSW.Rewards#131]
1.	Change existing menu item from “Events” to “Events – Upcoming”
2.	Add new flyout menu (left nav) item for ‘Events - Attended’
a.	Show hashtag for current event
b.	Indicate that points can be earned for tweeting this hashtag
c.	Show who else is at the event
3.	Ensure data is consistent to distinguish events: e.g.
a.	Adam’s talk at NDC becomes “NDC – Chinafy your App”
b.	Jason’s talk at NDC becomes “NDC – Clean Architecture”

**Comment by matt-goldman** [comment]
Superseded by v2 design
