### ISSUE TITLE
Bug - Trophy emoji does not show for claimed rewards in app

### ISSUE THREAD

**Issue by AndreasLengkeek** [SSWConsulting/SSW.Rewards#138]
As per my conversation with @MattGoldmanSSW 

The Prizes are not showing a trophy emoji if they have been claimed:
![image](https://user-images.githubusercontent.com/10122406/95804891-b4b0df80-0d4f-11eb-90c8-e8d889e59095.png)
Figure: Jean has not claimed any prizes

![image](https://user-images.githubusercontent.com/10122406/95804916-c7c3af80-0d4f-11eb-8916-95fcd9016910.png)
Figure: This shows the missing trophy emojis

[AB#57488](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57488)

**Comment by matt-goldman** [comment]
No longer relevant as this is not shown in v2
