### ISSUE TITLE
App - Dev Profile Scrolling Animation

### ISSUE THREAD

**Issue by AndreasLengkeek** [SSWConsulting/SSW.Rewards#150]
To: @MattGoldmanSSW 
cc: @adamcogan 

In the Dev Profiles section of the app, it would be great if we had a scroll in animation.

[AB#57870](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57870)

**Comment by matt-goldman** [comment]
Completed by: https://github.com/SSWConsulting/SSW.Rewards/pull/241
