### ISSUE TITLE
App - Points for social media

### ISSUE THREAD

**Issue by AndreasLengkeek** [SSWConsulting/SSW.Rewards#151]
To: @MattGoldmanSSW 
cc: @adamcogan 

It would be great if we could award points for people following or linking social media accounts to SSW

[AB#57871](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/57871)

**Comment by JackDevAU** [comment]
This can now be done through the admin portal
