### ISSUE TITLE
🐛 SSW Rewards | QR Code Scanning Bug

### ISSUE THREAD

**Issue by JoshuaBandsma** [SSWConsulting/SSW.Rewards#155]
To: @gregharrisssw 
CC: @adamcogan @Matt-Goldman

# Expected Behavior
Install the SSW App, then scan an SSW QR code, and see points earnt.

# Current Behavior
BUG Upon scanning an SSW QR code with a new SSW Rewards account, an error occurs stating, "Already Scanned!"

- Steps to Reproduce -
Install the app on iOS.
Log in.
Scan Adam's QR Code

[AB#60391](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/60391)

**Comment by matt-goldman** [comment]
Update: Identified that this issue affects accounts created with Facebook or Microsoft. Local (non-OIDC) accounts are working fine. Facebook and Microsoft IDPs removed from B2C until we can get it working.

**Comment by matt-goldman** [comment]
Resolved by migration to IdentityServer.
