### ISSUE TITLE
App - SSW Rewards progress bars

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.Rewards#156]
As per my email with Matt G, I am adding an issue to add rewards progress bars to the SSW Rewards app.

Having progress bars that show how far you are from the next reward will gamify the app and make clients feel more inclined to use it.

[AB#60481](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/60481)

**Comment by matt-goldman** [comment]
Resolved by v2 design
