### ISSUE TITLE
Admin Portal: Manage dev profiles (add, remove, edit)

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards#171]
cc: @JackDevAU 

Description:

See list below. Some of this functionality has already been built. Goal is to review the functionality, ensure it aligns with the acceptance criteria below, **and release.**

Acceptance criteria:

* See a list of dev profiles currently shown in the app
* Add a developer profile (including bio and pictures)
* Edit a developer profile (including bio and pictures)
* Remove a developer profile (archive? /  soft-delete / active/inactive)
* Updates reflected in mobile app

**Comment by JackDevAU** [comment]
cc: @AndreasLengkeek @matt-goldman 

> - [x] See a list of dev profiles currently shown in the app

Already implemented .
Fixed a bug with the filter

> - [x] Add a developer profile (including bio and pictures)

This was already working :) 

> - [x] Edit a developer profile (including bio and pictures)

Already implemented.
 Fixed a bug which was duplicating Profiles on edit

> - [x] Remove a developer profile (archive? / soft-delete / active/inactive)

Currently this is a hard delete. Should this be changed? 

> - [x] Updates reflected in mobile app

Currently only updates on launch of the application 

### Current Concerns:

Profile images are only retrieved if the **name matches**. Instead, should an **id** or **url path** be tied to a `StaffMember`?

**Comment by JackDevAU** [comment]
Update: 

> Currently this is a hard delete. Should this be changed?

Yes, this has now been changed to soft delete (A new field was added to the Staff table - `isDeleted` ) 

> Profile images are only retrieved if the name matches. Instead, should an id or url path be tied to a StaffMember?

This has also been changed to use `ID` instead of a name.

These changes have been merged into Dev for testing with the following PR's
 [#3867](https://dev.azure.com/ssw/SSW.Rewards/_git/SSW.Rewards.Admin/pullrequest/3867) and https://github.com/SSWConsulting/SSW.Rewards/pull/180
