### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards#173]
As a user of the Admin Portal
I want to be able to send push notifications
So that I can let app users know about events, talks, draws, prizes etc.

Acceptance criteria:
1. The admin portal has a 'Send Notification' area
2. Admin portal users can send a notification
3. iOS users receive the notification as a Push notification
4. Android users receive the notification as a Push notification

Technologies:
* Xamarin (mobile app)
* React 🤢 (admin portal)
* Azure Notification Hub (cloud)
* Google Firebase (Android notifications)
* Apple Push Notifications Service (iOS notifications)

Subtasks:
- [x] #193 
- [x] #194 
- [x] #195 
- [ ] #205

**Comment by AndreasLengkeek** [comment]
Spike - Educate yourself on how to connect Xamarin to Push Notifications
