### ISSUE TITLE
Admin Portal: Implement Auth using Identity

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Rewards#177]
Description:

See list below. Currently the Admin Portal is using an unofficial and no longer supported authentication package [react-azure-adb2c](https://github.com/jamesrandall/react-azure-adb2c). This package hasn't been updated in over 4 years. This is also believed to be causing the issue with the password reset, where on the final stage you are redirected to an invalid url causing the process to fail. 

Acceptance criteria:

- [ ] Remove the `react-azure-adb2c` package 
- [ ] Replace with a supported and official solution `oidc-client`

**Comment by matt-goldman** [comment]
Note: This needs to be updated to reflect the move to IdentityServer. We need to replace `react-azure-adbdc` with `IdentityModel.OidcClient`
