### ISSUE TITLE
Admin portal: add edit/delete functionality

### ISSUE THREAD

**Issue by camillars** [SSWConsulting/SSW.Rewards#178]
Cc: @matt-goldman @AndreasLengkeek 

Hi Matt and Andreas
  
### Pain

An events person not familiar with the SSW Rewards can add an event as an achievement by mistake twice - ideally, we would need to delete it so there is no confusion. 

It would be nice to see a delete or edit button for managing events' QR codes in the admin portal.

### Tasks

- [x] Add funtionality
- [x] Get it checked by an admin

### Screenshots

![image](https://user-images.githubusercontent.com/53064613/161479448-e811ad72-91e2-4768-9aaf-9fc88851833f.png)

Thanks!

**Comment by matt-goldman** [comment]
Completed by @JackDevAU
