### ISSUE TITLE
DevOps - Increase version of mobile apps on release

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards#192]
Move push to App Stores onto separate branch (follow release branch pattern)

**Comment by jianganna7** [comment]
Alright, I think I'll stick to what I've done already in https://github.com/SSWConsulting/SSW.Rewards/pull/218 for this task.

For simplicity, we will manually create release branch and attach tag `i.e. release/v1.1.1` to allow tags be extracted upon merging into main.

The workflow should be: 
1. Manually create a release branch and attach version tag 
2. Merge release branch into main 
3. Triggers app versioning automation

Worth mentioning, only upon push to `main` from a `release` branch(with version tags) will it trigger deployment to App Center. All other branches into main will only build but not deploy.

**Comment by matt-goldman** [comment]
Duplicate: #206
