### ISSUE TITLE
Set up Push Notification Services and Azure Notification Hub

### ISSUE THREAD

**Issue by jianganna7** [SSWConsulting/SSW.Rewards#193]
- [x] Create a Firebase project and enable Firebase Cloud Messaging for Android
- [x] Create a Provisioning Profile
- [x] Create a p8 certificate for Notification Hubs
- [x] Create a Notification Hub and configure with APNS and FCM information

**Comment by JackDevAU** [comment]
cc: @matt-goldman @lukecookssw @jianganna7 

We now have 2 Azure Notification Hubs.

**SSWRewards** = Production
**SSWRewardsDev** = Development

We currently only have the production environments setup (APNS & FCM). Before going live we should create and update the following,

- [ ] Create a APNS sandbox certificate for development use
- [ ] Create a FCM for development use
- [ ] Document what secrets we need to add the the deployment pipeline (Prod & Dev)

![image](https://user-images.githubusercontent.com/57518417/168752444-385dc9de-10a6-498d-b93d-3c5437a6b1dc.png)
**Figure: SSWRewards Azure Notifications Hubs Namespace**

**Comment by JackDevAU** [comment]
Closing and moving comment to a new issue: https://github.com/SSWConsulting/SSW.Rewards/issues/287
