### ISSUE TITLE
Mobile - Fix android QR crash

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Rewards#289]
When an android user scans a QR code, the app crashes. 

- [ ] Action a fix

**Comment by matt-goldman** [comment]
Note: This is caused by a Xamarin bug. See: https://github.com/xamarin/Xamarin.Forms/issues/14952.

Testing the suggested workaround in the linked issue.

**Comment by matt-goldman** [comment]
✅ Done! Suggested workaround mentioned above was successfully.

See: https://youtu.be/KBHLwj3_T5c
