### ISSUE TITLE
Neither authentication nor password reset are working

### ISSUE THREAD

**Issue by n-crrn** [SSWConsulting/SSW.Rewards#295]
SSW.Rewards user accounts are inaccessible through both the Android and iOS apps. Attempts to reset the account password do not result in a reset email being sent. Account username and password were known to be good.

No further information is provided from the interface. When returning from the web interface login screen, the app displays the message "Something went wrong there, please try again later." Screenshots attached of Android interface with account name blanked.
<img src='https://user-images.githubusercontent.com/6274048/174921759-5aa35ba6-f63f-4769-80eb-dba175c51182.jpg' width=30%/>
<img src='https://user-images.githubusercontent.com/6274048/174921761-aff5c6f0-df27-4fec-9b7b-24673dc63ee3.jpg' width=30%/>
<img src='https://user-images.githubusercontent.com/6274048/174921754-abb9826e-4923-4f4a-8212-c1dc679736bf.jpg' width=30%/>

**Comment by matt-goldman** [comment]
Hi @n-crrn 

We updated SSW Rewards to work with a new instance of IdentityServer (previously was Azure AD B2C). The accounts and data are still there in the SSW Rewards database (associated by email address), so no points or achievements have been lost in this migration. However we didn't migrate accounts from B2C to IDS. So you will need to follow the sign-up process; once you've done this you'll have access to all your existing data.

We've updated the UI in the app to better reflect this. Apologies for not communicating this change effectively. Please try again and let me know if you're still stuck.

**Comment by n-crrn** [comment]
Hi @matt-goldman,

I signed up again and can confirm that points/achievements were correctly associated after logging in. Thank you.
