### ISSUE TITLE
Home page: selecting "USE THIS PICTURE" without selecting a picture closes the app

### ISSUE THREAD

**Issue by leehawkinsssw** [SSWConsulting/SSW.Rewards#298]
Tested using SSW Rewards app version 2.0 on Samsung Galaxy J5 Pro.

On the app Home page, I selected the camera icon (as I don't have a profile photo set) then selected "USE THIS PICTURE" without selecting a photo. The app closed.

It would be better if the "USE THIS PICTURE" button was only enabled after a photo has been taken/selected.

**Comment by matt-goldman** [comment]
✅ Done! The use picture button is now disabled when a picture is not selected.

See: https://youtu.be/5rQSuhfMtLs
