### ISSUE TITLE
Spike QR code scanning feasibility within MAUI framework

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards#310]

**Comment by matt-goldman** [comment]
Not feasible at this time

**Comment by matt-goldman** [comment]
UPDATE: New library from Jonathan Peppers, it's now working. (Tested in CommBox client project).

**Comment by matt-goldman** [comment]
UPDATE: New library from Jonathan Peppers, it's now working. (Tested in CommBox client project)
See: https://github.com/Redth/ZXing.Net.Maui
